version: 2.0
jobs:
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: cd consegna
      - run: g++ -Wall -std=c++11 labo2_main.cpp labo2_aux.cpp labo2_sort.cpp -o labo
      - run: ./labo

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest
